---
title: "Portal within"
date: 2018-10-08
---

title: Here it is
author: miradoblackwarrior
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  All things are open for discussion. Nature. Science. Philosophy. Art. Human Condition. 

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
